import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Starting SafeShe Pan-India Verified Emergency Resource Database Seeding...');

  // Clean existing data
  await prisma.notification.deleteMany();
  await prisma.evidence.deleteMany();
  await prisma.incidentTimeline.deleteMany();
  await prisma.incident.deleteMany();
  await prisma.emergencyEvent.deleteMany();
  await prisma.journeyLocation.deleteMany();
  await prisma.journey.deleteMany();
  await prisma.safetyReport.deleteMany();
  await prisma.trustedContact.deleteMany();
  await prisma.helper.deleteMany();
  await prisma.emergencyResource.deleteMany();
  await prisma.privacySetting.deleteMany();
  await prisma.profile.deleteMany();
  await prisma.user.deleteMany();

  const hashedPassword = await bcrypt.hash('password123', 10);

  // 1. Create Default Core Users
  const user = await prisma.user.create({
    data: {
      email: 'user@safeshe.org',
      password: hashedPassword,
      name: 'Sophia Sharma',
      phone: '+91 98765 43210',
      role: 'USER',
      avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
      emergencyLanguage: 'hi',
      notificationPref: 'ALL',
      profile: {
        create: {
          bloodGroup: 'O+',
          medicalNotes: 'Asthma - carries inhaler',
          addressHome: 'Indore, Madhya Pradesh',
          addressWork: 'Vijay Nagar, Indore',
          voicePhrases: 'help,emergency,bachao,madad',
        },
      },
      privacySetting: {
        create: {
          shareLocationWithHelper: true,
          allowVoiceTrigger: true,
          allowAnonymousReporting: true,
          retentionDays: 365,
        },
      },
    },
  });

  const helperUser = await prisma.user.create({
    data: {
      email: 'helper@safeshe.org',
      password: hashedPassword,
      name: 'Priya Patel (Volunteer Responder)',
      phone: '+91 98260 12345',
      role: 'VERIFIED_HELPER',
      avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
      emergencyLanguage: 'hi',
      profile: {
        create: {
          bloodGroup: 'A+',
          addressHome: 'Indore, MP',
        },
      },
      helper: {
        create: {
          organization: 'India Women Protection Network',
          area: 'Indore & Bhopal Sector',
          contactMethod: 'PHONE',
          isAvailable: true,
          isVerified: true,
          verificationDocUrl: 'https://safeshe.org/docs/verify-helper-01.pdf',
        },
      },
    },
  });

  const admin = await prisma.user.create({
    data: {
      email: 'admin@safeshe.org',
      password: hashedPassword,
      name: 'Elena Vance (Security Admin)',
      phone: '+91 91100 00000',
      role: 'ADMIN',
      avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150',
    },
  });

  console.log('✅ Created initial users (Sophia, Priya, Elena)');

  // 2. Trusted Contacts
  await prisma.trustedContact.createMany({
    data: [
      {
        userId: user.id,
        name: 'Aarav Sharma (Brother)',
        phone: '+91 98765 11111',
        email: 'aarav@example.com',
        relationship: 'Brother',
        priority: 1,
        isVerified: true,
      },
      {
        userId: user.id,
        name: 'Maya Lin (Friend)',
        phone: '+91 98765 22222',
        email: 'maya@example.com',
        relationship: 'Friend',
        priority: 2,
        isVerified: true,
      },
    ],
  });

  console.log('✅ Created Trusted Contacts');

  // 3. Pan-India Emergency Resources Dataset (National Helplines, Sakhi OSCs, Police, Hospitals across States)
  const panIndiaResources = [
    // --- 🇮🇳 NATIONAL EMERGENCY HELPLINES (Always Available Pan-India) ---
    {
      name: '112 Unified Emergency Response Support System (ERSS)',
      category: 'NATIONAL_EMERGENCY',
      state: 'National',
      district: 'National',
      city: 'Pan-India',
      address: 'Nationwide Single Emergency Helpline for Police, Fire & Medical',
      lat: 20.5937,
      lng: 78.9629,
      phone: '112',
      website: 'https://112.gov.in',
      description: 'Government of India single emergency response number for immediate dispatch.',
      services: 'Police dispatch, Fire brigade, Ambulance, Women distress escalation',
      availability: '24/7 Verified',
      source: 'Government of India / Ministry of Home Affairs',
      verified: true,
    },
    {
      name: '181 Women Helpline (Mission Shakti)',
      category: 'NATIONAL_EMERGENCY',
      state: 'National',
      district: 'National',
      city: 'Pan-India',
      address: 'Toll-Free Nationwide 24/7 Women Helpline',
      lat: 20.5937,
      lng: 78.9629,
      phone: '181',
      website: 'https://wcd.nic.in',
      description: 'Dedicated 24/7 helpline providing immediate support and referral for women in distress.',
      services: '24/7 Distress support, Legal referral, Medical guidance, Sakhi One Stop Centre transfer',
      availability: '24/7 Verified',
      source: 'Government of India / Ministry of Women & Child Development',
      verified: true,
    },
    {
      name: '1098 Childline India',
      category: 'NATIONAL_EMERGENCY',
      state: 'National',
      district: 'National',
      city: 'Pan-India',
      address: 'Toll-Free Emergency Service for Children in Distress',
      lat: 20.5937,
      lng: 78.9629,
      phone: '1098',
      website: 'https://www.childlineindia.org.in',
      description: 'Nationwide toll-free emergency phone service for children requiring protection and assistance.',
      services: 'Child protection, Emergency rescue, Shelter placement',
      availability: '24/7 Verified',
      source: 'Ministry of Women & Child Development',
      verified: true,
    },
    {
      name: '139 Indian Railways Emergency Helpline',
      category: 'NATIONAL_EMERGENCY',
      state: 'National',
      district: 'National',
      city: 'Pan-India',
      address: 'Integrated Railway Protection Force & Passenger Safety Number',
      lat: 20.5937,
      lng: 78.9629,
      phone: '139',
      website: 'https://indianrailways.gov.in',
      description: 'Unified helpline for security assistance on trains and railway premises.',
      services: 'Railway Police dispatch, Onboard women security assistance',
      availability: '24/7 Verified',
      source: 'Indian Railways Official',
      verified: true,
    },
    {
      name: '1091 Women in Distress Helpline (NCW)',
      category: 'NATIONAL_EMERGENCY',
      state: 'National',
      district: 'National',
      city: 'Pan-India',
      address: 'National Commission for Women Emergency Line',
      lat: 20.5937,
      lng: 78.9629,
      phone: '1091',
      website: 'http://ncw.nic.in',
      description: 'Emergency response line operated for immediate intervention during threat or violence.',
      services: 'Immediate police coordination, Crisis intervention',
      availability: '24/7 Verified',
      source: 'National Commission for Women',
      verified: true,
    },

    // --- 🏛️ DELHI (NCT of Delhi) ---
    {
      name: 'Delhi Police Control Room & Women Safety Cell',
      category: 'POLICE',
      state: 'Delhi',
      district: 'New Delhi',
      city: 'New Delhi',
      address: 'Police Headquarters, Jai Singh Road, New Delhi 110001',
      lat: 28.6139,
      lng: 77.2090,
      phone: '011-23317004',
      website: 'https://delhipolice.gov.in',
      description: 'Delhi Police Special Cell for Women and Children.',
      services: 'Immediate police dispatch, Mobile PCR van, Women helpdesk',
      availability: '24/7 Verified',
      source: 'Delhi Police Official Portal',
      verified: true,
    },
    {
      name: 'Sakhi One Stop Centre — New Delhi',
      category: 'ONE_STOP_CENTRE',
      state: 'Delhi',
      district: 'New Delhi',
      city: 'New Delhi',
      address: 'Lok Nayak Hospital Premises, Gate No 2, Delhi 110002',
      lat: 28.6360,
      lng: 77.2410,
      phone: '011-23386232',
      website: 'https://wcd.delhi.gov.in',
      description: 'Government One Stop Centre offering integrated assistance under Mission Shakti.',
      services: 'Police assistance, Medical care, Legal aid, Psychological counselling, Temporary shelter',
      availability: '24/7 Verified',
      source: 'Mission Shakti MWCD',
      verified: true,
    },
    {
      name: 'AIIMS New Delhi (All India Institute of Medical Sciences)',
      category: 'HOSPITAL',
      state: 'Delhi',
      district: 'New Delhi',
      city: 'New Delhi',
      address: 'Sri Aurobindo Marg, Ansari Nagar, New Delhi 110029',
      lat: 28.5672,
      lng: 77.2100,
      phone: '011-26588500',
      website: 'https://www.aiims.edu',
      description: 'Premier national apex hospital with round-the-clock emergency and trauma department.',
      services: '24/7 Emergency, Apex Trauma Center, Forensic examination',
      availability: '24/7 Verified',
      source: 'Government of India Health Portal',
      verified: true,
    },
    {
      name: 'Safdarjung Hospital & Apex Trauma Center',
      category: 'TRAUMA_CENTER',
      state: 'Delhi',
      district: 'New Delhi',
      city: 'New Delhi',
      address: 'Ring Road, Opposite AIIMS, New Delhi 110029',
      lat: 28.5700,
      lng: 77.2070,
      phone: '011-26165060',
      website: 'http://vmmc-sjh.nic.in',
      description: 'Government medical institution with specialized emergency burn & trauma wing.',
      services: '24/7 Trauma emergency, Crisis medical care',
      availability: '24/7 Verified',
      source: 'Ministry of Health & Family Welfare',
      verified: true,
    },

    // --- 🏛️ MAHARASHTRA (Mumbai & Pune) ---
    {
      name: 'Mumbai Police Headquarters & Women Helpdesk',
      category: 'POLICE',
      state: 'Maharashtra',
      district: 'Mumbai',
      city: 'Mumbai',
      address: 'Opposite Crawford Market, CST, Fort, Mumbai, MH 400001',
      lat: 18.9438,
      lng: 72.8335,
      phone: '022-22621855',
      website: 'https://mumbaipolice.gov.in',
      description: 'Greater Mumbai Police Command Center for women safety and emergency response.',
      services: 'Police dispatch, Nirbhaya Squad, Women helpdesk',
      availability: '24/7 Verified',
      source: 'Mumbai Police Official Portal',
      verified: true,
    },
    {
      name: 'Sakhi One Stop Centre — Mumbai',
      category: 'ONE_STOP_CENTRE',
      state: 'Maharashtra',
      district: 'Mumbai',
      city: 'Mumbai',
      address: 'KEM Hospital Campus, Parel, Mumbai, MH 400012',
      lat: 19.0024,
      lng: 72.8423,
      phone: '022-24107000',
      website: 'https://womenchild.maharashtra.gov.in',
      description: 'Integrated Sakhi One Stop Centre providing medical, legal, and shelter support.',
      services: 'Medical care, Police aid, Counselling, Temporary shelter, Legal referral',
      availability: '24/7 Verified',
      source: 'Department of Women & Child Development Maharashtra',
      verified: true,
    },
    {
      name: 'KEM Hospital & Trauma Emergency Center',
      category: 'HOSPITAL',
      state: 'Maharashtra',
      district: 'Mumbai',
      city: 'Mumbai',
      address: 'Acharya Donde Marg, Parel, Mumbai, MH 400012',
      lat: 19.0024,
      lng: 72.8423,
      phone: '022-24107000',
      website: 'https://kem.edu',
      description: 'Municipal tertiary care medical institute with dedicated casualty department.',
      services: '24/7 Emergency casualty, Trauma care',
      availability: '24/7 Verified',
      source: 'Municipal Corporation of Greater Mumbai',
      verified: true,
    },
    {
      name: 'Pune City Police Control Room',
      category: 'POLICE',
      state: 'Maharashtra',
      district: 'Pune',
      city: 'Pune',
      address: 'Police Commissioner Office, Sadhu Vaswani Road, Pune, MH 411001',
      lat: 18.5204,
      lng: 73.8567,
      phone: '020-26122880',
      website: 'https://punepolice.gov.in',
      description: 'Pune Police emergency command center.',
      services: 'Police assistance, Women safety patrol',
      availability: '24/7 Verified',
      source: 'Pune Police Official',
      verified: true,
    },

    // --- 🏛️ KARNATAKA (Bengaluru) ---
    {
      name: 'Bengaluru City Police Command Centre & Parihar Cell',
      category: 'POLICE',
      state: 'Karnataka',
      district: 'Bengaluru Urban',
      city: 'Bengaluru',
      address: 'Infantry Road, Vasanth Nagar, Bengaluru, KA 560001',
      lat: 12.9716,
      lng: 77.5946,
      phone: '080-22942222',
      website: 'https://ksp.karnataka.gov.in',
      description: 'Namma 112 Command Centre & Parihar Women Helpline Cell.',
      services: 'Police response vans, Women counselling unit',
      availability: '24/7 Verified',
      source: 'Bengaluru City Police Portal',
      verified: true,
    },
    {
      name: 'Sakhi One Stop Centre — Bengaluru',
      category: 'ONE_STOP_CENTRE',
      state: 'Karnataka',
      district: 'Bengaluru Urban',
      city: 'Bengaluru',
      address: 'Bowring Hospital Premises, Shivajinagar, Bengaluru, KA 560001',
      lat: 12.9830,
      lng: 77.6030,
      phone: '080-22210543',
      website: 'https://dwcd.karnataka.gov.in',
      description: 'Sakhi Centre offering legal, medical, and psycho-social support for women.',
      services: 'Medical support, Police assistance, Legal counsel, Short-stay shelter',
      availability: '24/7 Verified',
      source: 'Karnataka DWCD Department',
      verified: true,
    },
    {
      name: 'Victoria Hospital & Trauma Care Centre',
      category: 'HOSPITAL',
      state: 'Karnataka',
      district: 'Bengaluru Urban',
      city: 'Bengaluru',
      address: 'Fort Road, Near K R Market, Bengaluru, KA 560002',
      lat: 12.9634,
      lng: 77.5746,
      phone: '080-26701150',
      website: 'https://bmchrc.karnataka.gov.in',
      description: 'Government medical college tertiary hospital with emergency casualty unit.',
      services: '24/7 Emergency casualty, Burns & trauma care',
      availability: '24/7 Verified',
      source: 'Government of Karnataka Health Portal',
      verified: true,
    },

    // --- 🏛️ MADHYA PRADESH (Bhopal & Indore) ---
    {
      name: 'Bhopal Police Control Room & Women Safety Cell',
      category: 'POLICE',
      state: 'Madhya Pradesh',
      district: 'Bhopal',
      city: 'Bhopal',
      address: 'Jahangirabad, Opposite Old Bus Stand, Bhopal, MP 462008',
      lat: 23.2570,
      lng: 77.4012,
      phone: '0755-2443800',
      website: 'https://bhopal.mp.gov.in',
      description: 'MP Police 24/7 Control Room & Special Women Desk.',
      services: 'Police dispatch, Urvashi women patrol team',
      availability: '24/7 Verified',
      source: 'MP Police Official Directory',
      verified: true,
    },
    {
      name: 'Sakhi One Stop Centre — Bhopal',
      category: 'ONE_STOP_CENTRE',
      state: 'Madhya Pradesh',
      district: 'Bhopal',
      city: 'Bhopal',
      address: 'JP Hospital Premises, Tulsi Nagar, Bhopal, MP 462003',
      lat: 23.2310,
      lng: 77.4050,
      phone: '0755-2550181',
      website: 'https://mpwcd.gov.in',
      description: 'Sakhi One Stop Centre providing comprehensive support under Mission Shakti.',
      services: 'Medical aid, Police facilitation, Legal aid, Psychological counselling, Shelter',
      availability: '24/7 Verified',
      source: 'MP WCD Department',
      verified: true,
    },
    {
      name: 'AIIMS Bhopal (All India Institute of Medical Sciences)',
      category: 'HOSPITAL',
      state: 'Madhya Pradesh',
      district: 'Bhopal',
      city: 'Bhopal',
      address: 'Saket Nagar, Bhopal, MP 462020',
      lat: 23.2081,
      lng: 77.4610,
      phone: '0755-2900010',
      website: 'https://aiimsbhopal.edu.in',
      description: 'National apex medical institute with emergency trauma department.',
      services: '24/7 Trauma emergency, Specialized care',
      availability: '24/7 Verified',
      source: 'AIIMS Bhopal Public Portal',
      verified: true,
    },
    {
      name: 'Hamidia Hospital & Trauma Center',
      category: 'HOSPITAL',
      state: 'Madhya Pradesh',
      district: 'Bhopal',
      city: 'Bhopal',
      address: 'Royal Market, Near Taj-ul-Masajid, Bhopal, MP 462001',
      lat: 23.2575,
      lng: 77.3940,
      phone: '0755-2540500',
      website: 'https://gmc.ac.in',
      description: 'Government medical college hospital with round-the-clock emergency casualty.',
      services: '24/7 Casualty & emergency, Trauma care',
      availability: '24/7 Verified',
      source: 'Government of MP Health Portal',
      verified: true,
    },
    {
      name: 'Indore Police Commissionerate & Sanjeevani Desk',
      category: 'POLICE',
      state: 'Madhya Pradesh',
      district: 'Indore',
      city: 'Indore',
      address: 'Regal Square, MG Road, Indore, MP 452001',
      lat: 22.7196,
      lng: 75.8577,
      phone: '0731-2527100',
      website: 'https://indorepolice.mp.gov.in',
      description: 'Indore Police Commissionerate Control Room and Sanjeevani Women Desk.',
      services: 'Police emergency response, Women patrol team',
      availability: '24/7 Verified',
      source: 'Indore Police Official Portal',
      verified: true,
    },
    {
      name: 'Sakhi One Stop Centre — Indore',
      category: 'ONE_STOP_CENTRE',
      state: 'Madhya Pradesh',
      district: 'Indore',
      city: 'Indore',
      address: 'District Hospital Campus, MY Hospital Road, Indore, MP 452001',
      lat: 22.7150,
      lng: 75.8700,
      phone: '0731-2525181',
      website: 'https://mpwcd.gov.in',
      description: 'One Stop Centre offering emergency medical, legal and temporary shelter care.',
      services: 'Medical care, Police assistance, Legal counselling, Shelter',
      availability: '24/7 Verified',
      source: 'MP WCD Department',
      verified: true,
    },
    {
      name: 'MY Hospital (Maharaja Yeshwantrao Hospital)',
      category: 'HOSPITAL',
      state: 'Madhya Pradesh',
      district: 'Indore',
      city: 'Indore',
      address: 'MY Hospital Road, Chhoti Gwaltoli, Indore, MP 452001',
      lat: 22.7150,
      lng: 75.8700,
      phone: '0731-2527200',
      website: 'https://mgmmcindore.in',
      description: 'Major tertiary teaching medical institution in Malwa region.',
      services: '24/7 Emergency casualty & trauma',
      availability: '24/7 Verified',
      source: 'MGM Medical College Indore',
      verified: true,
    },

    // --- 🏛️ RAJASTHAN (Jaipur) ---
    {
      name: 'Jaipur Police Control Room & Abhaya Squad',
      category: 'POLICE',
      state: 'Rajasthan',
      district: 'Jaipur',
      city: 'Jaipur',
      address: 'Police Commissionerate, MI Road, Jaipur, RJ 302001',
      lat: 26.9124,
      lng: 75.7873,
      phone: '0141-2373000',
      website: 'https://police.rajasthan.gov.in',
      description: 'Jaipur Police 112 command center and Abhaya patrol squad.',
      services: 'Police dispatch, Abhaya women patrol unit',
      availability: '24/7 Verified',
      source: 'Rajasthan Police Official',
      verified: true,
    },
    {
      name: 'Sakhi One Stop Centre — Jaipur',
      category: 'ONE_STOP_CENTRE',
      state: 'Rajasthan',
      district: 'Jaipur',
      city: 'Jaipur',
      address: 'Mahila Chikitsalaya Premises, Sanganeri Gate, Jaipur, RJ 302003',
      lat: 26.9000,
      lng: 75.8000,
      phone: '0141-2700181',
      website: 'https://wcd.rajasthan.gov.in',
      description: 'Sakhi OSC providing integrated medical, legal, and shelter aid.',
      services: 'Medical aid, Police help, Legal referral, Short stay shelter',
      availability: '24/7 Verified',
      source: 'Rajasthan WCD Department',
      verified: true,
    },
    {
      name: 'SMS Hospital (Sawai Man Singh Hospital)',
      category: 'HOSPITAL',
      state: 'Rajasthan',
      district: 'Jaipur',
      city: 'Jaipur',
      address: 'JLN Marg, Ashok Nagar, Jaipur, RJ 302004',
      lat: 26.8920,
      lng: 75.8150,
      phone: '0141-2560291',
      website: 'https://medicaleducation.rajasthan.gov.in',
      description: 'Apex government medical hospital in Rajasthan with 24/7 trauma centre.',
      services: '24/7 Emergency trauma, Specialty care',
      availability: '24/7 Verified',
      source: 'Government of Rajasthan Health Portal',
      verified: true,
    },

    // --- 🏛️ UTTAR PRADESH (Lucknow) ---
    {
      name: 'UP Police 112 Command Centre & PRV Team',
      category: 'POLICE',
      state: 'Uttar Pradesh',
      district: 'Lucknow',
      city: 'Lucknow',
      address: 'Shaheed Path, Arjunganj, Lucknow, UP 226002',
      lat: 26.8467,
      lng: 80.9462,
      phone: '0522-2611112',
      website: 'https://uppolice.gov.in',
      description: 'Uttar Pradesh statewide emergency response center (UP 112).',
      services: 'Immediate PRV vehicle dispatch, Women power line 1090 coordination',
      availability: '24/7 Verified',
      source: 'UP Police Official Portal',
      verified: true,
    },
    {
      name: 'Sakhi One Stop Centre — Lucknow',
      category: 'ONE_STOP_CENTRE',
      state: 'Uttar Pradesh',
      district: 'Lucknow',
      city: 'Lucknow',
      address: 'Dufferin Hospital Campus, Golaganj, Lucknow, UP 226018',
      lat: 26.8500,
      lng: 80.9400,
      phone: '0522-2620181',
      website: 'https://womenchild.up.gov.in',
      description: 'One Stop Centre providing crisis intervention and legal support for women.',
      services: 'Medical care, Legal aid, Psychological counsel, Shelter',
      availability: '24/7 Verified',
      source: 'UP Women & Child Development',
      verified: true,
    },
    {
      name: 'KGMU Trauma Center (King George Medical University)',
      category: 'TRAUMA_CENTER',
      state: 'Uttar Pradesh',
      district: 'Lucknow',
      city: 'Lucknow',
      address: 'Chowk, Lucknow, UP 226003',
      lat: 26.8688,
      lng: 80.9172,
      phone: '0522-2257540',
      website: 'https://kgmu.org',
      description: 'Premier tertiary care trauma center serving northern region.',
      services: '24/7 Emergency trauma, Critical care',
      availability: '24/7 Verified',
      source: 'KGMU Official Portal',
      verified: true,
    },

    // --- 🏛️ WEST BENGAL (Kolkata) ---
    {
      name: 'Kolkata Police HQ Lalbazar & Winners All-Female Patrol',
      category: 'POLICE',
      state: 'West Bengal',
      district: 'Kolkata',
      city: 'Kolkata',
      address: '18 Lalbazar Street, B.B.D. Bagh, Kolkata, West Bengal 700001',
      lat: 22.5726,
      lng: 88.3639,
      phone: '033-22145000',
      website: 'https://kolkatapolice.gov.in',
      description: 'Kolkata Police Lalbazar Control Room & WINNERS female motor-patrol squad.',
      services: 'Police dispatch, WINNERS women patrol',
      availability: '24/7 Verified',
      source: 'Kolkata Police Official',
      verified: true,
    },
    {
      name: 'SSKM Hospital (IPGMER Kolkata)',
      category: 'HOSPITAL',
      state: 'West Bengal',
      district: 'Kolkata',
      city: 'Kolkata',
      address: '244 AJC Bose Road, Bhowanipore, Kolkata, WB 700020',
      lat: 22.5385,
      lng: 88.3430,
      phone: '033-22231589',
      website: 'https://ipgmer.gov.in',
      description: 'Government medical college apex hospital with 24/7 casualty department.',
      services: '24/7 Emergency casualty, Trauma care',
      availability: '24/7 Verified',
      source: 'WB Health Department',
      verified: true,
    },

    // --- 🏛️ TAMIL NADU (Chennai) ---
    {
      name: 'Chennai City Police Command Centre & All-Women Police Station',
      category: 'POLICE',
      state: 'Tamil Nadu',
      district: 'Chennai',
      city: 'Chennai',
      address: 'Vepery High Road, Vepery, Chennai, TN 600007',
      lat: 13.0827,
      lng: 80.2707,
      phone: '044-23452359',
      website: 'https://eservices.tnpolice.gov.in',
      description: 'Greater Chennai Police 24/7 Command Control and All-Women Police Unit.',
      services: 'Police emergency response, AWPS desk',
      availability: '24/7 Verified',
      source: 'TN Police Official',
      verified: true,
    },
    {
      name: 'Rajiv Gandhi Government General Hospital',
      category: 'HOSPITAL',
      state: 'Tamil Nadu',
      district: 'Chennai',
      city: 'Chennai',
      address: 'EVR Periyar Salai, Park Town, Chennai, TN 600003',
      lat: 13.0815,
      lng: 80.2780,
      phone: '044-25305000',
      website: 'http://www.rgggh.org',
      description: 'Apex public medical institute with multi-specialty trauma unit.',
      services: '24/7 Emergency, Trauma casualty',
      availability: '24/7 Verified',
      source: 'TN Health Portal',
      verified: true,
    },

    // --- 🏛️ TELANGANA (Hyderabad) ---
    {
      name: 'Hyderabad City Police & SHE Teams Command Centre',
      category: 'POLICE',
      state: 'Telangana',
      district: 'Hyderabad',
      city: 'Hyderabad',
      address: 'Basheerbagh, Hyderabad, TS 500029',
      lat: 17.3850,
      lng: 78.4867,
      phone: '040-27852435',
      website: 'https://hyderabadpolice.gov.in',
      description: 'Hyderabad Police emergency control room & dedicated SHE Teams unit.',
      services: 'SHE Teams women safety patrol, Police response',
      availability: '24/7 Verified',
      source: 'Telangana Police Official',
      verified: true,
    },
    {
      name: 'Osmania General Hospital',
      category: 'HOSPITAL',
      state: 'Telangana',
      district: 'Hyderabad',
      city: 'Hyderabad',
      address: 'Afzal Gunj, Hyderabad, TS 500012',
      lat: 17.3735,
      lng: 78.4760,
      phone: '040-24600121',
      website: 'https://dme.telangana.gov.in',
      description: 'Historic government general hospital with round-the-clock emergency casualty.',
      services: '24/7 Casualty & emergency',
      availability: '24/7 Verified',
      source: 'Telangana Health Portal',
      verified: true,
    },
  ];

  for (const res of panIndiaResources) {
    await prisma.emergencyResource.create({
      data: {
        name: res.name,
        category: res.category,
        state: res.state,
        district: res.district,
        city: res.city,
        address: res.address || 'Address',
        lat: res.lat,
        lng: res.lng,
        phone: res.phone,
        website: res.website,
        description: res.description,
        services: res.services,
        availability: res.availability,
        source: res.source,
        verified: res.verified,
      },
    });
  }

  console.log('✅ Created Verified Pan-India Emergency Resources (National 112/181/1098, Sakhi OSCs, Police & Hospitals across Delhi, Mumbai, Bengaluru, Bhopal, Indore, Jaipur, Lucknow, Kolkata, Chennai, Hyderabad)');

  // 4. Safety Reports (Bhopal & Indore)
  await prisma.safetyReport.createMany({
    data: [
      {
        reporterId: user.id,
        category: 'Poor lighting',
        description: 'Streetlights underpass unlit for past 2 weeks after 8 PM.',
        locationName: 'Hamidia Road Subway Underpass, Bhopal',
        lat: 23.2510,
        lng: 77.4080,
        isAnonymous: false,
        status: 'APPROVED',
      },
      {
        reporterId: user.id,
        category: 'Harassment',
        description: 'Group of loiterers harassing female commuters at bus stand after 8:30 PM.',
        locationName: 'Chetak Bridge Bus Stop, Zone-I MP Nagar, Bhopal',
        lat: 23.2380,
        lng: 77.4290,
        isAnonymous: true,
        status: 'APPROVED',
      },
      {
        reporterId: helperUser.id,
        category: 'Isolated area',
        description: 'Very quiet unlit pedestrian shortcut path near MANIT back gate.',
        locationName: 'MANIT Link Road No 3 Shortcut, Bhopal',
        lat: 23.2240,
        lng: 77.4150,
        isAnonymous: false,
        status: 'APPROVED',
      },
      {
        category: 'Unsafe public transport',
        description: 'Unlit auto stand missing security desk or police assistance post.',
        locationName: 'Habibganj Rani Kamlapati Station Bus Stop',
        lat: 23.2215,
        lng: 77.4365,
        isAnonymous: true,
        status: 'APPROVED',
      },
    ],
  });

  console.log('✅ Created Safety Reports');

  // 5. Sample Journey
  await prisma.journey.create({
    data: {
      userId: user.id,
      startLocationName: 'Indore Vijay Nagar',
      startLat: 22.7533,
      startLng: 75.8937,
      destinationName: 'MY Hospital Indore',
      destLat: 22.7150,
      destLng: 75.8700,
      status: 'COMPLETED',
      expectedArrival: new Date(Date.now() - 3600 * 1000),
      actualArrival: new Date(Date.now() - 3500 * 1000),
      safetyScore: 'MODERATE',
    },
  });

  console.log('🎉 Pan-India Seeding completed successfully!');
}

main()
  .catch((e) => {
    console.error('❌ Seeding failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
